Remove @zeit/next-css from package.json
**Remove @zeit/next-css since it is not needed for last next version and cause internal issues while building the app:**

Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

error - ./node_modules/@shopify/polaris/dist/styles.css
TypeError: Cannot read property 'tapAsync' of undefined